# Generated by Django 2.1.5 on 2022-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
