# Generated by Django 2.1.5 on 2022-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_management',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense_management',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
