# Generated by Django 2.1.5 on 2022-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMapp', '0002_auto_20221225_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='expense_management',
            name='description',
            field=models.TextField(max_length=1300),
        ),
    ]
