# Generated by Django 2.1.5 on 2022-12-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMapp', '0003_auto_20221231_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_management',
            name='Sign_In',
            field=models.ManyToManyField(blank=True, null=True, to='EMapp.Sign_In'),
        ),
        migrations.AlterField(
            model_name='sign_in',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
